const carsDataBase = [
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    compectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: 'https://ibb.co/18hZz3j',
  }
];

export default carsDataBase;
