const URL = 'https://i.ibb.co/6N45SYR/';

const carsDataBase = [
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  },
  {
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    preview: `${URL}/mers.png`,
  }
];

export default carsDataBase;
