import { Car } from '../types/Car';

const carsDataBase: Array<Car> = [
  {
    id: '12fd850svg6',
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'GLS-Class',
    color: 'black',
    year: 2022,
    price: 10890000,
    enginePower: 380,
    engineVolume: 4,
    preview: `https://i.ibb.co/6N45SYR/mers1.png`,
  },
  {
    id: '30f7s648f6g',
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'A-Class',
    color: 'black',
    year: 2021,
    price: 2920000,
    enginePower: 306,
    engineVolume: 2,
    preview: `https://i.ibb.co/TkQSVyb/mers2.jpg`,
  },
  {
    id: '69ghns54vs2',
    brand: 'Mercedes',
    model: 'Mercedes-Benz',
    complectation: 'AMG-GT',
    color: 'white',
    year: 2020,
    price: 10890000,
    enginePower: 550,
    engineVolume: 4,
    preview: `https://i.ibb.co/rmsFM3s/mers3.jpg`,
  },
  {
    id: '7568hdxbs43',
    brand: 'Audi',
    model: 'A8',
    complectation: 'Full',
    color: 'white',
    year: 2022,
    price: 8890000,
    enginePower: 550,
    engineVolume: 4,
    preview: `https://i.ibb.co/N3YsFyS/audi1.jpg`,
  },
  {
    id: '36dfv96hsnx',
    brand: 'Audi',
    model: 'A4',
    complectation: 'Avant',
    color: 'grey',
    year: 2021,
    price: 5890000,
    enginePower: 300,
    engineVolume: 2.5,
    preview: `https://i.ibb.co/TwcBy0p/audi2.jpg`,
  },
  {
    id: '354gsv9g5hs',
    brand: 'Audi',
    model: 'Q7',
    complectation: 'Full',
    color: 'grey',
    year: 2022,
    price: 6890000,
    enginePower: 390,
    engineVolume: 3,
    preview: `https://i.ibb.co/Qc45Qsj/audi3.jpg`,
  },
  {
    id: '345dfc2bsr4',
    brand: 'Porsche',
    model: '911 Carrera',
    complectation: '4 GTS',
    color: 'white',
    year: 2020,
    price: 12420000,
    enginePower: 490,
    engineVolume: 3.5,
    preview: `https://i.ibb.co/Xx7zY8x/porsche1.jpg`,
  },
  {
    id: '95gsbxhj58h',
    brand: 'Porsche',
    model: 'Cayenne',
    complectation: 'Full',
    color: 'white',
    year: 2021,
    price: 9420000,
    enginePower: 350,
    engineVolume: 3.5,
    preview: `https://i.ibb.co/RcZghm2/porsche2.jpg`,
  },
  {
    id: '35dlthjvb4n',
    brand: 'Porsche',
    model: 'Taycan',
    complectation: 'Full',
    color: 'white',
    year: 2022,
    price: 16420000,
    enginePower: 600,
    engineVolume: 5,
    preview: `https://i.ibb.co/HV3B73x/porsche3.jpg`,
  }
];

export default carsDataBase;
