const employeesDataBase = {
  admin: {
    id: '46g7dvbdndn',
    login: 'toni-stark',
    password: 89143978701,
    fullName: 'Амельченко Антон Олегович',
    email: 'anton-amelchenko@mail.ru',
    phoneNumber: '8-914-777-22-03',
    position: 'Администратор',
  },
  sellers: [
    {
      id: '46g7dvb3g54',
      login: 'nikIvanov',
      password: 123321,
      fullName: 'Иванов Николай Константинович',
      email: 'nikolay-ivanov@mail.ru',
      phoneNumber: '8-914-111-22-03',
      position: 'Продавец',
    },
    {
      id: '3fg76k7dndn',
      login: 'egVas',
      password: 123321,
      fullName: 'Егоров Василий Петрович',
      email: 'vasiliy-egorov@mail.ru',
      phoneNumber: '8-322-453-23-94',
      position: 'Продавец',
    },
  ],
  marketers: [
    {
      id: '09g7dvbfnl8',
      login: 'markTven',
      password: 123321,
      fullName: 'Астер Марк Фрейд',
      email: 'mark-carry@mail.ru',
      phoneNumber: '8-914-232-22-13',
      position: 'Маркетолог',
    },
    {
      id: '84n2dvscxdn',
      login: 'dimasikemployeesriy_Shevchuk',
      password: 123321,
      fullName: 'Шевчук Дмитрий Николаевич',
      email: 'dmitriy-shevchukv@mail.ru',
      phoneNumber: '8-111-223-56-94',
      position: 'Маркетолог',
    },
  ],
  mechanics: [
    {
      id: '06h7dvbdsx4',
      login: 'mihmih',
      password: 123321,
      fullName: 'Братов Михали Юрьевич',
      email: 'misha-brat@mail.ru',
      phoneNumber: '8-800-231-22-13',
      position: 'Механик',
    },
    {
      id: '06mmdvbnm67',
      login: 'semich',
      password: 123321,
      fullName: 'Иванов Семен Степанович',
      email: 'semenov-semen@mail.ru',
      phoneNumber: '8-567-765-56-94',
      position: 'Механик',
    },
  ],
  accountants: [
    {
      id: 'v3x7d90mn34v',
      login: 'kolyaKol',
      password: 123321,
      fullName: 'Градов Николай Алексеевич',
      email: 'nikola-tesla@mail.ru',
      phoneNumber: '8-999-777-66-55',
      position: 'Бухгалтер',
    },
    {
      id: '12bfl6sx54s',
      login: 'maric',
      password: 123321,
      fullName: 'Марисов Артур Маревич',
      email: 'maricov-artur@mail.ru',
      phoneNumber: '8-123-321-44-44',
      position: 'Бухгалтер',
    },
  ],
  governances: [
    {
      id: '23vd95gfns4',
      login: 'slavkal',
      password: 123321,
      fullName: 'Помидоров Вячеслав Александрович',
      email: 'pomidorich-slavyan@mail.ru',
      phoneNumber: '8-123-123-12-34',
      position: 'Управляющий',
    },
    {
      id: '5lfvx05683d',
      login: 'kirich',
      password: 123321,
      fullName: 'Антипов Кирил Васильевич',
      email: 'antipov-kiril@mail.ru',
      phoneNumber: '8-222-222-22-22',
      position: 'Управляющий',
    },
  ],
  systemAdministrators: [
    {
      id: 'lkdg402s4f4',
      login: 'borisLoh',
      password: 123321,
      fullName: 'Гренов Борис Борисович',
      email: 'boris-povis@mail.ru',
      phoneNumber: '8-345-678-32-43',
      position: 'Системный администратор',
    },
    {
      id: 'bsg405msh3j',
      login: 'antonioBanderas',
      password: 123321,
      fullName: 'Власов Антон Данилович',
      email: 'antoha-ahotna@mail.ru',
      phoneNumber: '8-955-324-58-68',
      position: 'Системный администратор',
    },
  ],
};

export default employeesDataBase;
