const dataBase = {
  admin: {
    login: 'toni-stark',
    password: 89143978701,
    fullName: 'Anton_Amelchenko',
    email: 'anton-amelchenko@mail.ru',
    phoneNumber: '8-914-777-22-03',
    position: 'admin',
  },
  sellers: [
    {
      login: 'nikIvanov',
      password: 123321,
      fullName: 'Nikolay_Ivanov',
      email: 'nikolay-ivanov@mail.ru',
      phoneNumber: '8-914-111-22-03',
      position: 'seller',
    },
    {
      login: 'egVas',
      password: 123321,
      fullName: 'Vasiliy_Egorov',
      email: 'vasiliy-egorov@mail.ru',
      phoneNumber: '8-322-453-23-94',
      position: 'seller',
    },
  ],
  marketers: [
    {
      login: 'markTven',
      password: 123321,
      fullName: 'Mark_Aster',
      email: 'mark-carry@mail.ru',
      phoneNumber: '8-914-232-22-13',
      position: 'marketer',
    },
    {
      login: 'dimasik',
      password: 123321,
      fullName: 'Dmitriy_Shevchuk',
      email: 'dmitriy-shevchukv@mail.ru',
      phoneNumber: '8-111-223-56-94',
      position: 'marketer',
    },
  ],
  mechanics: [
    {
      login: 'mihmih',
      password: 123321,
      fullName: 'Mihail_Bratov',
      email: 'misha-brat@mail.ru',
      phoneNumber: '8-800-231-22-13',
      position: 'mechanic',
    },
    {
      login: 'semich',
      password: 123321,
      fullName: 'Semen_Ivanov',
      email: 'semenov-semen@mail.ru',
      phoneNumber: '8-567-765-56-94',
      position: 'mechanic',
    },
  ],
  accountants: [
    {
      login: 'kolyaKol',
      password: 123321,
      fullName: 'Nikolay_Gradov',
      email: 'nikola-tesla@mail.ru',
      phoneNumber: '8-999-777-66-55',
      position: 'accountant',
    },
    {
      login: 'maric',
      password: 123321,
      fullName: 'Artur_Maricov',
      email: 'maricov-artur@mail.ru',
      phoneNumber: '8-123-321-44-44',
      position: 'accountant',
    },
  ],
  governances: [
    {
      login: 'slavkal',
      password: 123321,
      fullName: 'Vechaslav_Pomidorov',
      email: 'pomidorich-slavyan@mail.ru',
      phoneNumber: '8-123-123-12-34',
      position: 'governance',
    },
    {
      login: 'kirich',
      password: 123321,
      fullName: 'Kiril_Antipov',
      email: 'antipov-kiril@mail.ru',
      phoneNumber: '8-222-222-22-22',
      position: 'governance',
    },
  ],
  systemAdministrators: [
    {
      login: 'borisLoh',
      password: 123321,
      fullName: 'Boris_Grenov',
      email: 'boris-povis@mail.ru',
      phoneNumber: '8-345-678-32-43',
      position: 'systemAdministrator',
    },
    {
      login: 'antonioBanderas',
      password: 123321,
      fullName: 'Anton_Vlasov',
      email: 'antoha-ahotna@mail.ru',
      phoneNumber: '8-955-324-58-68',
      position: 'systemAdministrator',
    },
  ],
};

export default dataBase;
